pipeline {

	agent any 
	
	stages{
	
		stage('Compile stage ')
		{
		
			steps
			{
				
				git 'https://github.com/TanumayDhar/devSample.git'
				echo 'building the application ....'			
			}
			
		
		}
		
		
	}
	
		stage('Test stage ')
			{
			steps
			{
				echo 'Test the application...'			
			}
			
		
		
		
	}	
	
		stage('Deploy stage ')
		{
		
			steps
			{
				echo 'Deploy the application ...'			
			}
			
		
	}
		
}	
	
	
