pipeline {

	agent any 
	
	stages{
	
		stage('Compile stage ')
		{
		
			steps
			{
				
				git 'https://github.com/TanumayDhar/devSample.git'
				echo 'building the application ....'			
			}
			
		
		}
		
		
	}
	
		
